### ISSUE TITLE
Unable to run.

### ISSUE THREAD

**Issue by jag959** [zhr85210078/node-mongodb-es-connector#5]
$ /usr/local/lib/node_modules/es-mongodb-sync# node app.js 

/usr/local/lib/node_modules/es-mongodb-sync/node_modules/mongo-oplog/lib/index.js:38
module.exports = (uri, options = {}) => {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/es-mongodb-sync/node_modules/mongo-oplog/index.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/es-mongodb-sync/lib/util/tail.js:3:18)
    at Module._compile (module.js:410:26)

**Comment by zhr85210078** [comment]
https://github.com/zhr85210078/es-connector-api
